FILE /tryCatch.kt
  FUN public fun test1(): kotlin.Unit
    BLOCK_BODY
      TRY_CATCH type=kotlin.Unit
        try: BLOCK type=kotlin.Unit origin=null
          CALL 'println(): Unit' type=kotlin.Unit origin=null
        catch e: BLOCK type=kotlin.Unit origin=null
          CALL 'println(): Unit' type=kotlin.Unit origin=null
        finally: BLOCK type=kotlin.Unit origin=null
          CALL 'println(): Unit' type=kotlin.Unit origin=null
  FUN public fun test2(): kotlin.Int
    BLOCK_BODY
      RETURN type=kotlin.Nothing from='test2(): Int'
        TRY_CATCH type=kotlin.Int
          try: BLOCK type=kotlin.Int origin=null
            CALL 'println(): Unit' type=kotlin.Unit origin=null
            CONST Int type=kotlin.Int value='42'
          catch e: BLOCK type=kotlin.Int origin=null
            CALL 'println(): Unit' type=kotlin.Unit origin=null
            CONST Int type=kotlin.Int value='24'
          finally: BLOCK type=kotlin.Unit origin=null
            CALL 'println(): Unit' type=kotlin.Unit origin=null
